name: Publish Docker image (backend)

on:
  push

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries (backend)
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push Docker image (backend example)
        uses: docker/build-push-action@v5
        with:
          context: ./example
          file: ./example/ssh-server-backend.Dockerfile
          push: true
          tags: example-ssh-server-backend:latest
